#!/usr/bin/env ruby

require 'rubygems'
require 'grooveshark'
require 'open-uri'
require 'colorize'
require 'cgi'

class SpotifyToMp3
  def initialize(log)
    @grooveshark = Grooveshark.new
    @spotify = Spotify.new
    @log = log
  end

  def download_song(spotify_uri)
    log("Getting song info for #{spotify_uri} from Spotify")
    track = @spotify.track(spotify_uri)
    filename = File.basename("#{track.artist()} - #{track.name()}.mp3".tr('/', '-'))
    if (File.exists?(filename))
      log("File #{filename} already exists, skipping")
      return
    end
    log("Getting download URL for \"#{track.artist()} - #{track.name()}\" from Grooveshark")
    url = @grooveshark.song_url(track.artist(), track.name())
    log("Downloading song")
    download_url(url, filename)
    log("Song downloaded to #{filename}")
  end

  private

  def log(message)
    @log.call(message)
  end

  def download_url(url, path)
    content = open(url).read
    file = open(path, 'wb')
    file.write(content)
    file.close
  end

  class Grooveshark
    def initialize
      @client = ::Grooveshark::Client.new
    end

    def song_url(artist, title)
      songs = @client.search_songs("#{artist} #{title}")
      song = songs.first # Fallback
      raise "Song not found" if song.nil?
      @client.get_song_url(song)
    end
  end

  class Spotify
    def track(uri)
      content = open('http://ws.spotify.com/lookup/1/.json?uri=' + CGI.escape(uri))
      json = JSON.parse(content.string)
      Track.new(json)
    end

    class Track
      def initialize(json)
        @json = json
      end

      def name
        @json['track']['name']
      end

      def artist
        @json['track']['artists'].first['name']
      end
    end
  end
end

spotifyToMp3 = SpotifyToMp3.new(lambda { |message| puts message })

ARGF.each do |spotify_uri|
  spotify_uri.strip!
  begin
    spotifyToMp3.download_song(spotify_uri)
  rescue
    puts "ERROR: #{$!}".red
  end
end
