require 'rubygems'
require 'grooveshark'
require 'open-uri'
require 'colorize'
require 'rest-client'
require 'fileutils'

require 'spotify_to_mp3/services'
require 'spotify_to_mp3/songs'
require 'spotify_to_mp3/sources'
require 'spotify_to_mp3/app'
